name: x_clone
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.5
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.6
  flutter_riverpod: ^2.3.6
  url_launcher: ^6.1.12
  dio: ^5.2.1+1
  hive_flutter: ^1.1.0
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  easy_localization: ^3.0.2
  build_runner: ^2.4.6
  json_annotation: ^4.8.1
  event_bus: ^2.0.0
  flutter_screenutil: ^5.8.2
  intl: ^0.18.0
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  pull_to_refresh: ^2.0.0
  image_picker: ^1.0.4
  flutter_native_splash: ^2.3.5
  font_awesome_flutter: ^10.6.0
  webview_flutter_plus: ^0.3.0+2
  webview_flutter: ^3.0.4


#flutter_native_splash:
#  color: "#ffffff"
#  image: "res/assets/logoLight.png"
#  #  background_image: "res/assets/logoLight.png"
#  android: true
#  ios: true
#  web: false
#  android_gravity: fill
#  ios_content_mode: scaleAspectFill
#  android_12:
#    color: "#ffffff"
#    image: "res/assets/logoLight.png"
#    #    background_image: "res/assets/logoLight.png"
#    android_gravity: fill










dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  json_serializable: ^6.7.1
  flutter_launcher_icons: "^0.13.1"

flutter:

  uses-material-design: true
  assets:
    - res/assets/
    - res/localization/
  fonts:
    - family: Roboto
      fonts:
        - asset: res/fonts/Roboto-Regular.ttf
